process.env.DEBUG = 'bessel_j, bessel_j_ex,J_bessel';
const libR = require('./dist/lib/libR');
let sd = new libR.rng.SuperDuper(0);
srt = libR.SignRank();
psignrank = srt.psignrank;
seq = libR.R.seq()();
student = libR.StudentT();
let w = libR.Wilcoxon(sd);
let bJ = libR.special.besselJ;
let rng = libR.rng;
let wh = new rng.WichmannHill(0);
let mm = new rng.MarsagliaMultiCarry(0);
let kn97 = new rng.KnuthTAOCP(0);
const kt2002 = new rng.KnuthTAOCP2002(0);
const lc = new rng.LecuyerCMRG(0);
sd.init(0);
lc.seed;
new Array(5).fill('').map(() => lc.unif_rand());