export * from "./distributions/beta";
export * from "./distributions/binomial";
export * from "./distributions/binomial-negative";
export * from "./distributions/cauchy";
export * from "./distributions/chi-2";
export * from "./distributions/exp";
export * from "./distributions/f-distro";
export * from "./distributions/gamma";
export * from "./distributions/geometric";
export * from "./distributions/hypergeometric";
export * from "./distributions/logis";
export * from "./distributions/lognormal";
export * from "./distributions/multinom";
export * from "./distributions/normal";
export * from "./distributions/poisson";
export * from "./distributions/signrank";
export * from "./distributions/student-t";
export * from "./distributions/tukey";
export * from "./distributions/uniform";
export * from "./distributions/weibull";
export * from "./distributions/wilcoxon";
export * from "./rng/index";
export * from "./special/bessel";
export * from "./special/gamma";
export * from "./special/beta";
export * from "./special/choose";
export { chebyshev_eval, chebyshev_init } from "./chebyshev";
export { hypot, log1p as log1pR } from "./alt/log/index";
//# sourceMappingURL=index.d.ts.map