export declare enum IRNGTypeEnum {
    KNUTH_TAOCP = "KNUTH_TAOCP",
    KNUTH_TAOCP2002 = "KNUTH_TAOCP2002",
    LECUYER_CMRG = "LECUYER_CMRG",
    MARSAGLIA_MULTICARRY = "MARSAGLIA_MULTICARRY",
    MERSENNE_TWISTER = "MERSENNE_TWISTER",
    SUPER_DUPER = "SUPER_DUPER",
    WICHMANN_HILL = "WICHMANN_HILL",
    USER_DEFINED = "USER_DEFINED"
}
//# sourceMappingURL=irng-type.d.ts.map